### PR TITLE
Update OPM version and use overwrite-latest option

### PR DESCRIPTION
**Pull request by JAORMX**
this ensures that the index that we're adding for the release is the
latest int he channel.

### CODE REVIEW

**Comment by jhrozek** [comment]
`make index-image` fails for me with:
```
Error: unable to pull quay.io/compliance-operator/compliance-operator-index:0.1.22: Error initializing source docker://quay.io/compliance-operator/compliance-operator-index:0.1.22: Error reading manifest 0.1.22 in quay.io/compliance-operator/compliance-operator-index: manifest unknown: manifest unknown
. exit status 125
Usage:
  opm index add [flags]
```
Is there a reason why we didn't push the 1.22 index images when the release was done?

**Comment by JAORMX** [comment]
@jhrozek I pushed to latest... pushing to a tag didn't really work for me... I need to update the Makefile.

**Comment by jhrozek** [comment]
For some reason that I didn't find out one of the nodes stopped responding until rebooted:
```
   "conditions": [
                    {
                        "lastHeartbeatTime": "2020-12-02T07:37:17Z",
                        "lastTransitionTime": "2020-12-02T07:38:05Z",
                        "message": "Kubelet stopped posting node status.",
                        "reason": "NodeStatusUnknown",
                        "status": "Unknown",
                        "type": "MemoryPressure"
                    },
                    {
                        "lastHeartbeatTime": "2020-12-02T07:37:17Z",
                        "lastTransitionTime": "2020-12-02T07:38:05Z",
                        "message": "Kubelet stopped posting node status.",
                        "reason": "NodeStatusUnknown",
                        "status": "Unknown",
                        "type": "DiskPressure"
                    },
                    {
                        "lastHeartbeatTime": "2020-12-02T07:37:17Z",
                        "lastTransitionTime": "2020-12-02T07:38:05Z",
                        "message": "Kubelet stopped posting node status.",
                        "reason": "NodeStatusUnknown",
                        "status": "Unknown",
                        "type": "PIDPressure"
                    },
                    {
                        "lastHeartbeatTime": "2020-12-02T07:37:17Z",
                        "lastTransitionTime": "2020-12-02T07:38:05Z",
                        "message": "Kubelet stopped posting node status.",
                        "reason": "NodeStatusUnknown",
                        "status": "Unknown",
                        "type": "Ready"
                    }
                ],
```
/retest

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 51af0999a9a44e8066a4cdbd910085c6968e9faf

**Pull request merged**
