### PR TITLE
doc: Improve the documentation of the Platform and Node scans, add a Platform scan CR

### PR DESCRIPTION
**Pull request by jhrozek**
Jira: OCPBUGSM-15302

### CODE REVIEW

**Comment by jhrozek** [comment]
CI is still not feeling well:
```
error: some steps failed:
  * could not run steps: step e2e-aws failed: template pod "e2e-aws" failed: pod didn't start running within 30 minutes: 
* Container artifacts is not ready with reason Completed and message 
* Container setup is not ready with reason Completed and message 
```

**Comment by jhrozek** [comment]
> Overall this looks good. However, should we have a subtitle just for spelling the differences between platform scans and node scans? Might be easier to find for folks

Sure, done

**Review by JAORMX — APPROVED** [review]
/lgtm

**Pull request merged**
