### PR TITLE
Handle errors in scan containers

### PR DESCRIPTION
**Pull request by JAORMX**
Previously, if the scan would fail, the scanner would remain in state running. This detects if there are errors in the container and moves the scan to a subsequent state.

Closes: #16

### CODE REVIEW

**Comment by JAORMX** [comment]
Note that currently it goes to state done. @mrogers950 @jhrozek what do you think about introducing a state "ERROR" ?

**Comment by jhrozek** [comment]
I think we could have a tri-state, depending on what the scanner returns:
 - 0 = COMPLIANT
 - 1 = FAILURE
 - 2 = NONCOMPLIANT

Note that this would require a change to the scanner image, right now the scanner always returns 0 if it produces report, compliant or not and only returns 1 if no report had been produced at all.

**Comment by jhrozek** [comment]
btw the patches look good as-is, what I proposed can be a follow-up. Let me know which way you prefer.

**Comment by JAORMX** [comment]
/hold

Lets wait for this to merge: https://github.com/openshift/release/pull/6005

**Comment by jhrozek** [comment]
btw does the PR work for you locally? I'm getting:
```
=== RUN   TestScanWithInvalidContentFails
--- FAIL: TestScanWithInvalidContentFails (148.14s)
    client.go:57: resource type ServiceAccount with namespace/name (openshift-compliance/compliance-operator) created
    client.go:57: resource type Role with namespace/name (openshift-compliance/compliance-operator) created
    client.go:57: resource type Role with namespace/name (openshift-compliance/scc-priv) created
    client.go:57: resource type ClusterRole with namespace/name (openshift-compliance/compliance-operator) created
    client.go:57: resource type RoleBinding with namespace/name (openshift-compliance/compliance-operator) created
    client.go:57: resource type RoleBinding with namespace/name (openshift-compliance/compliance-operator-scc-priv) created
    client.go:57: resource type ClusterRoleBinding with namespace/name (openshift-compliance/compliance-operator) created
    client.go:57: resource type Deployment with namespace/name (openshift-compliance/compliance-operator) created
    helpers.go:31: Initialized cluster resources
    wait_util.go:64: Waiting for full availability of compliance-operator deployment (0/1)
    wait_util.go:70: Deployment available (1/1)
    client.go:57: resource type  with namespace/name (openshift-compliance/example-scan) created
    helpers.go:60: Waiting for run of example-scan compliancescan ()
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    helpers.go:60: Waiting for run of example-scan compliancescan (RUNNING)
    e2e_test.go:69: timed out waiting for the condition
    client.go:75: resource type  with namespace/name (openshift-compliance/example-scan) successfully deleted
    client.go:75: resource type Deployment with namespace/name (openshift-compliance/compliance-operator) successfully deleted
    client.go:75: resource type ClusterRoleBinding with namespace/name (openshift-compliance/compliance-operator) successfully deleted
    client.go:75: resource type RoleBinding with namespace/name (openshift-compliance/compliance-operator-scc-priv) successfully deleted
    client.go:75: resource type RoleBinding with namespace/name (openshift-compliance/compliance-operator) successfully deleted
    client.go:75: resource type ClusterRole with namespace/name (openshift-compliance/compliance-operator) successfully deleted
    client.go:75: resource type Role with namespace/name (openshift-compliance/scc-priv) successfully deleted
    client.go:75: resource type Role with namespace/name (openshift-compliance/compliance-operator) successfully deleted
    client.go:75: resource type ServiceAccount with namespace/name (openshift-compliance/compliance-operator) successfully deleted
```

btw the reason I actually tried to patches (shame on me, before I just read the diff..) was that it looks to me like the condition in `aContainerHasFailed` would already be caught in the `foundPod.Status.Phase == corev1.PodFailed` because if any of the containers fail, the whole pod status is then failed, no?

**Comment by JAORMX** [comment]
@jhrozek there's a catch! currently CI uses the image from quay, so you need to run the operator with make run to test this out. But yeah, it worked for me locally. PodFailed will only happen when ALL of the pods fail. Which wasn't the case because of the long timeout.

**Comment by JAORMX** [comment]
This should fail without https://github.com/openshift/compliance-operator/pull/21

**Pull request merged**
