### PR TITLE
Add and fix relevant operator information in the CSV

### PR DESCRIPTION
**Pull request by JAORMX**
The CSV can display relevant information about the operator. We weren't
using this feature... So let's do it!

This adds information about the operator itself and it's capabilities.
This will help users find the operator in the OperatorHub.

It also sets the "suggested-namespace" annotation, which enables the OLM
to automatically create the required namespace.

Also, it fixes the installation capabilities to reflect what the
operator actually supports.

### CODE REVIEW

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now d895daa71d3e623bdf51197ef3803f1a14ee9c20

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 66c8a6d1d45a6c2f634847131d56ccaf170f17fc

**Comment by jhrozek** [comment]
```
 error: build error: error creating build container: Error initializing source docker://quay.io/complianceascode/ocp4:latest: Error reading manifest latest in quay.io/complianceascode/ocp4: received unexpected HTTP status: 500 Internal Server Error 
```
This lines up with a quay.io outage during today. I'll just reschedule.

**Review by jhrozek — APPROVED** [review]
/lgtm

**Comment by JAORMX** [comment]
Pull-request updated, HEAD is now 5567725c354d09b7e07ef4384537ddd115d94ed3

**Pull request merged**
