### PR TITLE
Updated v0.1.49 changelog broken URL

### PR DESCRIPTION
**Pull request by sheriff-rh**
First PR against compliance-operator, please let me know if I need to change my methods. Thanks!

I noticed the `deploying` URL provided does not direct to the intended section. I believe the author was trying to reach [this procedure](https://github.com/openshift/compliance-operator/blob/master/doc/install.md#deploying-with-helm).

Note: I guess I have "allow whitespace" disabled in Atom, so it removed some additional spaces at the end of lines automatically.

### CODE REVIEW

**Review by jhrozek — APPROVED** [review]
/lgtm
checked the link and the rendered changelog in your fork. The whitespace doesn't seem to matter, whitespace at the end of the lines is spurious anyway and renders fine.

**Comment by jhrozek** [comment]
lol:
```
EC2 VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
```
/retest

**Comment by Vincent056** [comment]
> lol:
> 
> ```
> EC2 VPC: VpcLimitExceeded: The maximum number of VPCs has been reached.
> ```
> 
> /retest

I think we have been had issues with CI cluster provisioning for a couple of days now since last week.

https://coreos.slack.com/archives/CBUT43E94/p1648118619528599

**Comment by rhmdnd** [comment]
LGTM - thanks!

**Comment by sheriff-rh** [comment]
`{  test "verify" failed: the pod ci-op-69s2tq35/verify failed after 10s (failed containers: ): OutOfcpu Pod Node didn't have enough resource: cpu, requested: 3438, used: 13271, capacity: 15890}`

**Pull request merged**
