### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by jhrozek** [comment]
One of the remediation tests timed out, let's just try again..

**Comment by isimluk** [comment]
Test failed again. Life is hard.

**Comment by isimluk** [comment]
No way! :face_with_head_bandage:

**Comment by jhrozek** [comment]
@isimluk can you rebase atop the current master? There were a bunch of issues in the test code we fixed recently, so without a rebase the e2e tests are likely to keep failing.

**Comment by isimluk** [comment]
> @isimluk can you rebase atop the current master? There were a bunch of issues in the test code we fixed recently, so without a rebase the e2e tests are likely to keep failing.

Gladly.

**Pull request merged**
