### PR TITLE
Two fixes in e2e tests so that we can fix our scanner image

### PR DESCRIPTION
**Pull request by jhrozek**
Our scanner image is currently broken in the sense that it does not report
non-compliance. Before we fix the scanner image, we need to make sure the
tests will keep passing.

The second patch fixes an embarassing issue where checks were not actually
checked..

### CODE REVIEW

**Comment by jhrozek** [comment]
oops, testSuiteScan expects to find some issues, let me fix that

**Comment by jhrozek** [comment]
Actually, let me just merge the scanner patch and regenerate the scanner. We need to find /some/ issues in that test.

What could be debated is whether it's good idea to check for exact name of remediations or if it would be better to check for a list of names we expect?

So now we have:
```
err = assertNumRemediations(f, suiteName, workerScanName, "worker", 2)
```
Maybe it would be better to have:
```
err = assertHasRemediations(f, suiteName, workerScanName, "worker", "remediation1")
err = assertHasRemediations(f, suiteName, workerScanName, "worker", "remediation2")
```
WDYT?

**Comment by JAORMX** [comment]
> Actually, let me just merge the scanner patch and regenerate the scanner. We need to find /some/ issues in that test.
> 
> What could be debated is whether it's good idea to check for exact name of remediations or if it would be better to check for a list of names we expect?
> 
> So now we have:
> 
> ```
> err = assertNumRemediations(f, suiteName, workerScanName, "worker", 2)
> ```
> 
> Maybe it would be better to have:
> 
> ```
> err = assertHasRemediations(f, suiteName, workerScanName, "worker", "remediation1")
> err = assertHasRemediations(f, suiteName, workerScanName, "worker", "remediation2")
> ```
> 
> WDYT?
 
Right, I prefer testing for the specific remediations.

**Comment by jhrozek** [comment]
OK, added another patch that checks the two expected remediations, any extra remediations are OK. This should be hopefully stable.

**Comment by JAORMX** [comment]
helpers.go:45: The ComplianceScan Result wasn't what we expected. Got 'COMPLIANT', expected 'NON-COMPLIANT' 

huh

**Comment by jhrozek** [comment]
I didn't merge the retval patch to the remediations_demo branch of the scanner I guess. Another reason to get rid of the script have all the logic in the operator.

**Pull request merged**
