### PR TITLE
Permit creating remediations from a ComplianceScan

### PR DESCRIPTION
**Pull request by jhrozek**
I'm opening this PR as a WIP because my cluster is cleaned up for the day
and I'd like to run the e2e tests to see if this is a viable approach..

### CODE REVIEW

**Comment by jhrozek** [comment]
of course there was a bug, let's see if this version fares any better while I work on a test

**Comment by JAORMX** [comment]
> The test is rather minimal, it just ensures that the remediations are created and all of them have the expected state. The test doesn't actually apply the remediations: let me know if that test would be preferable and I can change the patch. I just didn't want to introduce another non-parallel test for a corner case.

No, this is fine. It tests this specific functionality and that's exactly what we wanted.

**Comment by jhrozek** [comment]
@JAORMX the PR is ready for review

**Review by JAORMX — COMMENTED** [review]
/lgtm

**Comment by jhrozek** [comment]
This actually needs a rebase now:
```
# github.com/openshift/compliance-operator/tests/e2e [github.com/openshift/compliance-operator/tests/e2e.test]
tests/e2e/e2e_test.go:203:40: undefined: "github.com/openshift/compliance-operator/pkg/apis/compliance/v1alpha1".ScanLabel
FAIL	github.com/openshift/compliance-operator/tests/e2e [build failed]
```

**Pull request merged**
