### PR TITLE
Add verify make target (which also runs gosec)

### PR DESCRIPTION
**Pull request by JAORMX**
The verify target will run on CI and will do format checks, import
checks, as well as security static analysis on our code.

### CODE REVIEW

**Comment by JAORMX** [comment]
/assign jhrozek

can you test this as well?

**Comment by jhrozek** [comment]
LGTM, but can you run go mod tidy? Does it change go.mod for you in any way?

btw I tested this by running all the targets, so far they are silent (good).

**Comment by JAORMX** [comment]
funky, go mod tidy removes gosec, what the hell

**Pull request merged**
