### PR TITLE
Make assertRemediations use global timeout

### PR DESCRIPTION
**Pull request by JAORMX**
Instead of using a hardcoded timeout variable, lets make that function
use our constants instead...

This also ups the timeout to 15 min

### CODE REVIEW

**Comment by JAORMX** [comment]
/test e2e-aws

Installer error

**Comment by jhrozek** [comment]
retesting so I can watch the test interactively in CI..
/test e2e-aws

**Comment by jhrozek** [comment]
retesting so I can watch the test interactively in CI..
/test e2e-aws

**Pull request closed without merging**
