### PR TITLE
Enhance index image building to append new versions

### PR DESCRIPTION
**Pull request by JAORMX**
We were always building the index from scratch. This takes the previous
version into account and actually appens it to the currently existing
index. This way we can ship versions continuously upstream.

### CODE REVIEW

**Review by jhrozek — COMMENTED** [review]
Does this work for you? When I run `make index-image`, I get:
```
ERRO[0014] permissive mode disabled                      bundles="[quay.io/compliance-operator/compliance-operator-bundle:latest]" error="Bundle already added that provides package and csv"
Error: Bundle already added that provides package and csv
Usage:
  opm index add [flags]

Examples:
  # Create an index image from scratch with a single bundle image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus@sha256:a3ee653ffa8a0d2bbb2fabb150a94da6e878b6e9eb07defd40dc884effde11a0 --tag quay.io/operator-framework/monitoring:1.0.0
  
  # Add a single bundle image to an index image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus:0.15.0 --from-index quay.io/operator-framework/monitoring:1.0.0 --tag quay.io/operator-framework/monitoring:1.0.1
  
  # Add multiple bundles to an index and generate a Dockerfile instead of an image
  opm index add --bundles quay.io/operator-framework/operator-bundle-prometheus:0.15.0,quay.io/operator-framework/operator-bundle-prometheus:0.22.2 --generate

Flags:
  -i, --binary-image opm        container image for on-image opm command
  -u, --build-tool string       tool to build container images. One of: [docker, podman]. Defaults to podman. Overrides part of container-tool.
  -b, --bundles strings         comma separated list of bundles to add
  -c, --container-tool string   tool to interact with container images (save, build, etc.). One of: [docker, podman]
  -f, --from-index string       previous index to add to
      --generate                if enabled, just creates the dockerfile and saves it to local disk
  -h, --help                    help for add
      --mode string             graph update mode that defines how channel graphs are updated. One of: [replaces, semver, semver-skippatch] (default "replaces")
  -d, --out-dockerfile string   if generating the dockerfile, this flag is used to (optionally) specify a dockerfile name
      --permissive              allow registry load errors
  -p, --pull-tool string        tool to pull container images. One of: [none, docker, podman]. Defaults to none. Overrides part of container-tool.
  -t, --tag string              custom tag for container image being built

Global Flags:
      --skip-tls   skip TLS certificate verification for container image registries while pulling bundles or index

make: *** [Makefile:139: index-image] Error 3
```
Do I need some newer version of..something? My `opm` version is `version.Version{OpmVersion:"v1.13.8"`

**Comment by JAORMX** [comment]
You'd need to actually make an update. It fails saying that the version is already in the index. If we wanted this to be idempotent we'd maybe achieve that using the permissive flag

**Comment by jhrozek** [comment]
> You'd need to actually make an update. It fails saying that the version is already in the index. If we wanted this to be idempotent we'd maybe achieve that using the permissive flag

Aha interesting. That explains why this exact thing didn't work for me when I tried it some time ago :-)

**Review by jhrozek — APPROVED** [review]
/lgtm
given the explanation earlier

**Pull request merged**
