### PR TITLE
sync the release-4.6 branch with master

### PR DESCRIPTION
**Pull request by jhrozek**
Instead of risky cherry-picking, let's just merge the branches.

### CODE REVIEW

**Comment by mrogers950** [comment]
The last run failed because there was apparently no openshift-logging resources (nor was there an openshift-logging namespace!)

```File '/content/ssg-ocp4-ds.xml' found, using.
debug: Using profile xccdf_org.ssgproject.content_profile_moderate
debug: selected: xccdf_org.ssgproject.content_rule_audit_log_forwarding_enabled
debug: selected: xccdf_org.ssgproject.content_rule_ocp_allowed_registries
debug: selected: xccdf_org.ssgproject.content_rule_ocp_allowed_registries_for_import
debug: selected: xccdf_org.ssgproject.content_rule_ocp_idp_no_htpasswd
debug: <warning lang="en-US" category="general"><code class="ocp-api-endpoint">/apis/logging.openshift.io/v1/namespaces/openshift-logging/clusterlogforwarders/instance</code><code class="ocp-dump-location"><sub idref="xccdf_org.ssgproject.content_value_ocp_data_root" use="legacy" />/apis/logging.openshift.io/v1/namespaces/openshift-logging/clusterlogforwarders/instance</code>file.</warning>
debug: <warning lang="en-US" category="general"><code class="ocp-api-endpoint">/apis/config.openshift.io/v1/images/cluster</code><code class="ocp-dump-location"><sub idref="xccdf_org.ssgproject.content_value_ocp_data_root" use="legacy" />/apis/config.openshift.io/v1/images/cluster</code>file.</warning>
debug: <warning lang="en-US" category="general"><code class="ocp-api-endpoint">/apis/config.openshift.io/v1/images/cluster</code><code class="ocp-dump-location"><sub idref="xccdf_org.ssgproject.content_value_ocp_data_root" use="legacy" />/apis/config.openshift.io/v1/images/cluster</code>file.</warning>
debug: <warning lang="en-US" category="general"><code class="ocp-api-endpoint">/apis/config.openshift.io/v1/oauths/cluster</code><code class="ocp-dump-location"><sub idref="xccdf_org.ssgproject.content_value_ocp_data_root" use="legacy" />/apis/config.openshift.io/v1/oauths/cluster</code>file.</warning>
Fetching URI: '/apis/config.openshift.io/v1/clusteroperators/openshift-apiserver'
Fetching URI: '/apis/logging.openshift.io/v1/namespaces/openshift-logging/clusterlogforwarders/instance'
FATAL:Error fetching resources: the server could not find the requested resource
```

**Comment by JAORMX** [comment]
@mrogers950 that is expected... but it shouldn't fail like that. It should output a warning.

**Comment by JAORMX** [comment]
@jhrozek There seem to be commits missing from this PR. Specifically this one https://github.com/openshift/compliance-operator/commit/16f20aaaffbe2a0ee573438c9347132446d2654c

**Pull request merged**
